---
- name: Adding aliases
  loop: "{{ aliases | dict2items }}"
  lineinfile:
    path: /etc/hosts
    line: "{{ item.value }} {{ item.key }}"

- name: Configuring routes
  include_role:
    name: interface
  vars:
    interface_ip: "{{ interface.interface_ip }}"
    interface_default_gateway: "{{ interface.interface_default_gateway | default('') }}"
    interface_routes: "{{ interface.interface_routes | default([])}}"
  loop: "{{ routes }}"
  loop_control:
    loop_var: interface
...