hosts:
  - name: server
  - networks:
    server-switch: 192.168.20.5
  - name: client
  - networks:
    client-switch: 192.168.30.5

routers:
  - name: router
  - networks:
    server-switch: 192.168.20.1
    client-switch: 192.168.30.1
