---
# Basic configuration of all defined devices

- name: Including variables
  hosts: all
  tasks:

  - name: Including common variables
    include_vars:
      file: config.yml
      name: config

- name: Configuring hosts
  hosts: hosts
  become: yes
  roles:
    - hosts

- name: Configuring routers
  hosts: routers
  become: yes
  roles:
    - routers

- name: Configuring devices separately
  hosts: all
  become: yes
  tasks:
  - name: include role
    include_role:
      name: "{{ inventory_hostname }}"
...
