---

- name: disable qxl
  hosts:
      - routers
      - hosts
  gather_facts: yes
  become: yes
  tasks:
      - include_role:
            name: disable-qxl
        when: ansible_os_family == 'Debian'

- name: user access
  hosts:
      - user-accessible
  gather_facts: no
  become: yes
  tasks:
      - include_role:
            name: kypo-user-access
        vars:
            kypo_user_access_username: '{{ user }}'
            kypo_user_access_password: 'kypo'
        with_items:
            - kypo
            - root
        loop_control:
            loop_var: user


- name: Setting up Telnet server
  hosts: server
  become: yes
  roles:
    - server:
        username: test
        password: test
        telnet_port: 2323
...
